name: Test PR

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build
        run: |
          npm ci
          npm run build

  deploy_pr:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    env:
      MPKIT_URL: ${{ secrets.MPKIT_URL_PR }}
      MPKIT_EMAIL: ${{ secrets.MPKIT_EMAIL }}
      MPKIT_TOKEN: ${{ secrets.MPKIT_TOKEN }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Deploy
        run: |
          npm -g install @platformos/pos-cli
          pos-cli data clean --auto-confirm --include-schema
          pos-cli deploy
          pos-cli data import --path=./seed/data.zip --zip

  test_qa:
    needs: deploy_pr
    runs-on: ubuntu-latest
    container: platformos/testcafe:latest
    strategy:
      max-parallel: 1
    env:
      MPKIT_URL: ${{ secrets.MPKIT_URL_PR }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v1
      - name: Run testcafe
        run: |
          testcafe "chromium:headless" test --skip-js-errors
